title: beat-the-goalie-scratch2
hero_image: images/banner.png
description: beat-the-goalie-scratch2 description
version: 4
listed: false
copyedit: false
last_tested: "2019-02-12"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
